
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;
namespace Modelo
{
	public class C_CLAVESERVICIO
	{
		String		C_CLAVEPRODSERV;
		String		DESCRIPCION;

		public String c_claveprodserv
		{
			get { return this.C_CLAVEPRODSERV; }
			set { this.C_CLAVEPRODSERV = value;}
		}

		public String descripcion
		{
			get { return this.DESCRIPCION; }
			set { this.DESCRIPCION = value;}
		}

	}

	public static class metodos_C_CLAVESERVICIO
	{

        public static void insertarC_CLAVESERVICIO(String c_claveprodserv, String descripcion)
		{
			String Qry =@"INSERT INTO C_CLAVESERVICIO(c_ClaveProdServ,Descripcion)values(@c_ClaveProdServ,@Descripci )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_claveprodserv",c_claveprodserv);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();
		}

        public static void actualizarC_CLAVESERVICIO(String c_claveprodserv, String descripcion)
		{
			String Qry ="UPDATE C_CLAVESERVICIO SET c_ClaveProdServ = @c_ClaveProdServ, Descripcion = @Descripci WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_claveprodserv",c_claveprodserv);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();

        }

        public  static List<C_CLAVESERVICIO>  seleccionarC_CLAVESERVICIO()
		{
			List<C_CLAVESERVICIO> listC_CLAVESERVICIO = new List<C_CLAVESERVICIO>();
			String Qry = @"SELECT c_ClaveProdServ, Descripcion  FROM c_claveservicio";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				C_CLAVESERVICIO objC_CLAVESERVICIO = new C_CLAVESERVICIO();
				objC_CLAVESERVICIO.c_claveprodserv = datosItems["c_claveprodserv"].ToString() ;
				objC_CLAVESERVICIO.descripcion = datosItems["c_claveprodserv"].ToString()  +" - "+datosItems["descripcion"].ToString();
				listC_CLAVESERVICIO.Add( objC_CLAVESERVICIO);
			}
            datosItems.Close();
            d.Desconectar();
            return listC_CLAVESERVICIO;
        }
    }
}