
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;
namespace Modelo
{
	public class C_CVEUNIDAD
	{
		String		C_CLAVEUNIDAD;
		String		NOMBRE;

		public String c_claveunidad
		{
			get { return this.C_CLAVEUNIDAD; }
			set { this.C_CLAVEUNIDAD = value;}
		}

		public String nombre
		{
			get { return this.NOMBRE; }
			set { this.NOMBRE = value;}
		}

	}

	public static class metodos_C_CVEUNIDAD
	{

        public static void insertarC_CVEUNIDAD(String c_claveunidad, String nombre)
		{
			String Qry =@"INSERT INTO C_CVEUNIDAD(c_ClaveUnidad,Nombre)
values(
@c_ClaveUnidad,@Nomb )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_claveunidad",c_claveunidad);
			d.AsignarParametroCadena("@nombre",nombre);

			d.EjecutarComando();
            d.Desconectar();
        }

        public static void actualizarC_CVEUNIDAD(String c_claveunidad, String nombre)
		{
			String Qry ="UPDATE C_CVEUNIDAD SET c_ClaveUnidad = @c_ClaveUnidad, Nombre = @Nomb WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_claveunidad",c_claveunidad);
			d.AsignarParametroCadena("@nombre",nombre);

			d.EjecutarComando();
            d.Desconectar();
        }

        public static C_CVEUNIDAD seleccionarC_CVEUNIDAD(String unidad)
        {
            C_CVEUNIDAD objC_CVEUNIDAD = new C_CVEUNIDAD();
            String Qry = @"SELECT c_ClaveUnidad, Nombre  FROM c_cveunidad WHERE c_ClaveUnidad=@c_ClaveUnidad";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroCadena("@c_ClaveUnidad", unidad);
            DbDataReader datosItems = d.EjecutarConsulta();
            while (datosItems.Read())
            {

                objC_CVEUNIDAD.c_claveunidad = datosItems["c_claveunidad"].ToString();
                objC_CVEUNIDAD.nombre = datosItems["nombre"].ToString();
            }
            datosItems.Close();
            d.Desconectar();
            return objC_CVEUNIDAD;
        }

        public  static List<C_CVEUNIDAD>  seleccionarC_CVEUNIDAD()
		{
			List<C_CVEUNIDAD> listC_CVEUNIDAD = new List<C_CVEUNIDAD>();
			String Qry = @"SELECT c_ClaveUnidad, Nombre  FROM c_cveunidad";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				C_CVEUNIDAD objC_CVEUNIDAD = new C_CVEUNIDAD();
				objC_CVEUNIDAD.c_claveunidad = datosItems["c_claveunidad"].ToString();
				objC_CVEUNIDAD.nombre = datosItems["c_claveunidad"].ToString() +" - "+datosItems["nombre"].ToString();
				listC_CVEUNIDAD.Add( objC_CVEUNIDAD);
			}
            datosItems.Close();
            d.Desconectar();
            return listC_CVEUNIDAD; 
		}
	}
}