
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;
namespace Modelo
{
	public class C_FORMAPAGO
	{
		String		CFORMAPAGO;
		String		DESCRIPCION;

		public String c_formapago
		{
            get { return this.CFORMAPAGO; }
            set { this.CFORMAPAGO = value; }
		}

		public String descripcion
		{
			get { return this.DESCRIPCION; }
			set { this.DESCRIPCION = value;}
		}

	}

	public static class metodos_C_FORMAPAGO
	{

        public static void insertarC_FORMAPAGO(String c_formapago, String descripcion)
		{
			String Qry =@"INSERT INTO C_FORMAPAGO(c_Formapago,descripcion)
values(
@c_Formapago,@descripci )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_formapago",c_formapago);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();

        }

        public static void actualizarC_FORMAPAGO(String c_formapago, String descripcion)
		{
			String Qry ="UPDATE C_FORMAPAGO SET c_Formapago = @c_Formapago, descripcion = @descripci WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_formapago",c_formapago);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();

        }

        public static List<C_FORMAPAGO> seleccionarC_FORMAPAGO()
		{
			List<C_FORMAPAGO> listC_FORMAPAGO = new List<C_FORMAPAGO>();
            String Qry = @"SELECT c_Formapago, descripcion  FROM c_formapago";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);

			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				C_FORMAPAGO objC_FORMAPAGO = new C_FORMAPAGO();
				objC_FORMAPAGO.c_formapago = datosItems["c_formapago"].ToString();
				objC_FORMAPAGO.descripcion = datosItems["c_formapago"].ToString() +"-"+datosItems["descripcion"].ToString();
				listC_FORMAPAGO.Add( objC_FORMAPAGO);
			}
            datosItems.Close();
            d.Desconectar();

            return listC_FORMAPAGO; 
		}
	}
}