
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;
namespace Modelo
{
	public class C_MONEDA
	{
		String		CMONEDA;
		String		DESCRIPCION;

		public String c_moneda
		{
            get { return this.CMONEDA; }
            set { this.CMONEDA = value; }
		}

		public String descripcion
		{
			get { return this.DESCRIPCION; }
			set { this.DESCRIPCION = value;}
		}

	}

	public static class metodos_C_MONEDA
	{

        public static void insertarC_MONEDA(String c_moneda, String descripcion)
		{
			String Qry =@"INSERT INTO C_MONEDA(c_moneda,descripcion)
values(
@c_moneda,@descripci )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_moneda",c_moneda);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();

        }

        public static void actualizarC_MONEDA(String c_moneda, String descripcion)
		{
			String Qry ="UPDATE C_MONEDA SET c_moneda = @c_moneda, descripcion = @descripci WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@c_moneda",c_moneda);
			d.AsignarParametroCadena("@descripcion",descripcion);

			d.EjecutarComando();
            d.Desconectar();

        }

        public static List<C_MONEDA> validarC_MONEDA(string clave)
        {
            List<C_MONEDA> listC_MONEDA = new List<C_MONEDA>();
            String Qry = @"SELECT c_moneda, descripcion  FROM C_MONEDA WHERE c_moneda = @ID";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroCadena("@ID",  clave );
            DbDataReader datosItems = d.EjecutarConsulta();
            while (datosItems.Read())
            {
                C_MONEDA objC_MONEDA = new C_MONEDA();
                objC_MONEDA.c_moneda = datosItems["c_moneda"].ToString();
                objC_MONEDA.descripcion = datosItems["descripcion"].ToString();
                listC_MONEDA.Add(objC_MONEDA);
            }
            datosItems.Close();
            d.Desconectar();
            return listC_MONEDA;
        }

		public  static List<C_MONEDA>  seleccionarC_MONEDA(string clave)
		{
			List<C_MONEDA> listC_MONEDA = new List<C_MONEDA>();
            String Qry = @"SELECT c_moneda, descripcion  FROM C_MONEDA WHERE c_moneda like @ID  or descripcion  like @ID2";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
            d.AsignarParametroCadena("@ID", "%"+clave+"%");
            d.AsignarParametroCadena("@ID2", "%" + clave + "%");
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				C_MONEDA objC_MONEDA = new C_MONEDA();
				objC_MONEDA.c_moneda = datosItems["c_moneda"].ToString();
				objC_MONEDA.descripcion = datosItems["descripcion"].ToString();
				listC_MONEDA.Add( objC_MONEDA);
			}
            datosItems.Close();
            d.Desconectar();
            return listC_MONEDA; 
		}
	}
}