
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;
namespace Modelo
{
                            
    public class CLIENTES
    {
        Int32		ID_CLIENTE;
        String		NOMBRE;
        String		DIRECCION;
        String		CP;
        String		TELEFONO;
        String		CONTACTO;
        Double		CREDITO;
        String		RFC;
        String      Precio;
        String      EMAIL;

        public string email
        {
            get { return this.EMAIL; }
            set { this.EMAIL = value; }
        }

        public Int32 id_cliente
        {
            get { return this.ID_CLIENTE; }
            set { this.ID_CLIENTE = value;}
        }

        public String precio
        {
            get { return this.Precio; }
            set { this.Precio = value; }
        }

        public String nombre
        {
            get { return this.NOMBRE; }
            set { this.NOMBRE = value;}
        }

        public String direccion
        {
            get { return this.DIRECCION; }
            set { this.DIRECCION = value;}
        }

        public String cp
        {
            get { return this.CP; }
            set { this.CP = value;}
        }

        public String telefono
        {
            get { return this.TELEFONO; }
            set { this.TELEFONO = value;}
        }

        public String contacto
        {
            get { return this.CONTACTO; }
            set { this.CONTACTO = value;}
        }

        public Double credito
        {
            get { return this.CREDITO; }
            set { this.CREDITO = value;}
        }

        public String rfc
        {
            get { return this.RFC; }
            set { this.RFC = value;}
        }

    }
    public static class metodos_CLIENTES
    {
        public static void elimiarCLIENTES(Int32 id)
        {
            String Qry = @"DELETE FROM clientes where id_cliente=@id";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroEntero("@id", id);
            d.EjecutarComando();
            d.Desconectar();
        }

        public static void insertarCLIENTES(Int32 id_cliente, String nombre, String direccion, String cp, String telefono, String contacto,Double  credito, String rfc,string precio,string email)
        {
            String Qry = @"INSERT INTO clientes(id_cliente,nombre,direccion,cp,telefono,contacto,credito,rfc,precio,email)
            values(
            @id_cliente,@nombre,@direccion,@cp,@telefono,@contacto,@credito,@rfc,@precio,@email)";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroEntero("@id_cliente",id_cliente);
            d.AsignarParametroCadena("@nombre",nombre);
            d.AsignarParametroCadena("@direccion",direccion);
            d.AsignarParametroCadena("@cp",cp);
            d.AsignarParametroCadena("@telefono",telefono);
            d.AsignarParametroCadena("@contacto",contacto);
            d.AsignarParametroDouble("@credito",credito);
            d.AsignarParametroCadena("@rfc",rfc);
            d.AsignarParametroCadena("@precio", precio);
            d.AsignarParametroCadena("@email", email);
            d.EjecutarComando();
            d.Desconectar();

        }

        public static void actualizarCLIENTES(Int32 id_cliente, String nombre, String direccion, String cp, String telefono, String contacto, Int32 credito, String rfc, string precio, string email)
        {
            String Qry = "UPDATE clientes SET nombre = @nombre, direccion = @direccion, cp = @cp, telefono = @telefono, contacto = @contacto, credito = @credito, rfc = @rfc, precio=@precio , email=@email  WHERE id_cliente=@id_cliente";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroEntero("@id_cliente",id_cliente);
            d.AsignarParametroCadena("@nombre",nombre);
            d.AsignarParametroCadena("@direccion",direccion);
            d.AsignarParametroCadena("@cp",cp);
            d.AsignarParametroCadena("@telefono",telefono);
            d.AsignarParametroCadena("@contacto",contacto);
            d.AsignarParametroEntero("@credito",credito);
            d.AsignarParametroCadena("@rfc",rfc);
            d.AsignarParametroCadena("@precio", precio);
            d.AsignarParametroCadena("@email", email);
            d.EjecutarComando();
            d.Desconectar();
        }

        public static List<CLIENTES> seleccionarCLIENTES(string valorBuscado)
        {
            List<CLIENTES> listCLIENTES = new List<CLIENTES>();
            String Qry = @"SELECT id_cliente, nombre, direccion, cp, telefono, contacto, credito, rfc, precio,email FROM clientes WHERE nombre like @valorBuscado1 or rfc like @valorBuscado2";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroCadena("@valorBuscado1", "%" + valorBuscado + "%");
            d.AsignarParametroCadena("@valorBuscado2", "%" + valorBuscado + "%");
            DbDataReader datosItems = d.EjecutarConsulta();
            while (datosItems.Read())
            {
                CLIENTES objCLIENTES = new CLIENTES();
                objCLIENTES.id_cliente = Convert.ToInt32(datosItems["id_cliente"].ToString());
                objCLIENTES.nombre = datosItems["nombre"].ToString();
                objCLIENTES.direccion = datosItems["direccion"].ToString();
                objCLIENTES.cp = datosItems["cp"].ToString();
                objCLIENTES.telefono = datosItems["telefono"].ToString();
                objCLIENTES.contacto = datosItems["contacto"].ToString();
                objCLIENTES.credito = Convert.ToDouble(datosItems["credito"].ToString());
                objCLIENTES.rfc = datosItems["rfc"].ToString();
                objCLIENTES.precio = datosItems["precio"].ToString();
                objCLIENTES.email = datosItems["email"].ToString();
                listCLIENTES.Add(objCLIENTES);
            }
            datosItems.Close();
            d.Desconectar();
            return listCLIENTES;
        }

        public static List<CLIENTES>  seleccionarCLIENTES()
        {
            List<CLIENTES> listCLIENTES = new List<CLIENTES>(); 
            String Qry = @"SELECT id_cliente, nombre, direccion, cp, telefono, contacto, credito, rfc, precio,email FROM clientes ";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            DbDataReader datosItems = d.EjecutarConsulta();
            while(datosItems.Read())
            {
	            CLIENTES objCLIENTES        =   new CLIENTES();
	            objCLIENTES.id_cliente      =   Convert.ToInt32(datosItems["id_cliente"].ToString());
	            objCLIENTES.nombre          =   datosItems["nombre"].ToString();
	            objCLIENTES.direccion       =   datosItems["direccion"].ToString();
	            objCLIENTES.cp              =   datosItems["cp"].ToString();
	            objCLIENTES.telefono        =   datosItems["telefono"].ToString();
	            objCLIENTES.contacto        =   datosItems["contacto"].ToString();
	            objCLIENTES.credito         =   Convert.ToDouble(datosItems["credito"].ToString());
	            objCLIENTES.rfc             =   datosItems["rfc"].ToString();
                objCLIENTES.precio          =   datosItems["precio"].ToString();
                objCLIENTES.email           =   datosItems["email"].ToString();
                listCLIENTES.Add( objCLIENTES);
            }
            datosItems.Close();
            d.Desconectar();

            return listCLIENTES; 
        }
    }
}