
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
namespace nombre_del_namespace
{
	public class DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL
	{
		Int32		IDREGIMENFISCAL;
		String		REGIMENFISCAL;
		Int32		ESACTUAL;
		Int32		STATUS;

		public Int32 idregimenfiscal
		{
			get { return this.IDREGIMENFISCAL; }
			set { this.IDREGIMENFISCAL = value;}
		}

		public String regimenfiscal
		{
			get { return this.REGIMENFISCAL; }
			set { this.REGIMENFISCAL = value;}
		}

		public Int32 esactual
		{
			get { return this.ESACTUAL; }
			set { this.ESACTUAL = value;}
		}

		public Int32 status
		{
			get { return this.STATUS; }
			set { this.STATUS = value;}
		}

	}

	public static class metodos_DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL
	{

		public void insertarDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL(Int32 idregimenfiscal, String regimenfiscal, Int32 esactual, Int32 status)
		{
			String Qry =@"INSERT INTO DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL(IdRegimenFiscal)
values(
@IdRegimenFisc )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroEntero("@idregimenfiscal",idregimenfiscal);
			d.AsignarParametroCadena("@regimenfiscal",regimenfiscal);
			d.AsignarParametroEntero("@esactual",esactual);
			d.AsignarParametroEntero("@status",status);

			d.EjecutarComando();
		}

		public void actualizarDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL(Int32 idregimenfiscal, String regimenfiscal, Int32 esactual, Int32 status)
		{
			String Qry ="UPDATE DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL SET IdRegimenFiscal = @IdRegimenFisc WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroEntero("@idregimenfiscal",idregimenfiscal);
			d.AsignarParametroCadena("@regimenfiscal",regimenfiscal);
			d.AsignarParametroEntero("@esactual",esactual);
			d.AsignarParametroEntero("@status",status);

			d.EjecutarComando();
		}

		public  static List<DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL>  seleccionarDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL()
		{
			List<DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL> listDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL = new List<DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL>();
			String Qry =@"SELECT IdRegimenFisc  FROM DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL WHERE ID=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCALobjDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL = new DBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL();
				objDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL.idregimenfiscal = Convert.ToInt32(datosItems["idregimenfiscal"].ToString());
				objDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL.regimenfiscal = datosItems["regimenfiscal"].ToString();
				objDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL.esactual = Convert.ToInt32(datosItems["esactual"].ToString();
				objDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL.status = Convert.ToInt32(datosItems["status"].ToString();
				listDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL.Add( objDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL);
			}
			 return listDBO.SIEM_CLIENTES_CATALOGO_REGIMEN_FISCAL; 
		}
	}
}