//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using DCE05.Ejemplos.EstrellaUno.AccesoDatos;
namespace Modelo
{
                            
    public class PRODUCTOS
    {
        Int32		ID;
        String		CLAVE;
        String		DESCRIPCION;
        String		LINEA;
        String		UNIDADENTRADA;
        Int32		MINIMO;
        Int32		MAXIMO;
        String		MONEDA;
        Int32		EXISTENCIAS;
        Decimal		COSTO;
        Int32		CVEUNIDAD;
        Decimal		PRECIO1;
        Decimal		PRECIO2;
        Decimal		PRECIO3;
        String      FOTO;
        String      OBSERVACIONES;

        public Int32 id
        {
            get { return this.ID; }
            set { this.ID = value;}
        }

        public String clave
        {
            get { return this.CLAVE; }
            set { this.CLAVE = value;}
        }

        public String descripcion
        {
            get { return this.DESCRIPCION; }
            set { this.DESCRIPCION = value;}
        }

        public String linea
        {
            get { return this.LINEA; }
            set { this.LINEA = value;}
        }

        public String unidadentrada
        {
            get { return this.UNIDADENTRADA; }
            set { this.UNIDADENTRADA = value;}
        }

        public Int32 minimo
        {
            get { return this.MINIMO; }
            set { this.MINIMO = value;}
        }

        public Int32 maximo
        {
            get { return this.MAXIMO; }
            set { this.MAXIMO = value;}
        }

        public String moneda
        {
            get { return this.MONEDA; }
            set { this.MONEDA = value;}
        }

        public Int32 existencias
        {
            get { return this.EXISTENCIAS; }
            set { this.EXISTENCIAS = value;}
        }

        public Decimal costo
        {
            get { return this.COSTO; }
            set { this.COSTO = value;}
        }

        public Int32 cveunidad
        {
            get { return this.CVEUNIDAD; }
            set { this.CVEUNIDAD = value;}
        }

        public Decimal precio1
        {
            get { return this.PRECIO1; }
            set { this.PRECIO1 = value;}
        }

        public Decimal precio2
        {
            get { return this.PRECIO2; }
            set { this.PRECIO2 = value;}
        }

        public Decimal precio3
        {
            get { return this.PRECIO3; }
            set { this.PRECIO3 = value;}
        }

        public string foto
        {
            get { return this.FOTO; }
            set { this.FOTO = value;}
        }

        public string observaciones
        {
            get { return this.OBSERVACIONES; }
            set { this.OBSERVACIONES = value;}
        }

    }
    public static class metodos_PRODUCTOS
    {

        public static void insertarPRODUCTOS(Int32 id, String clave, String descripcion, String linea, String unidadentrada, Int32 minimo, Int32 maximo, String moneda, Int32 existencias, Decimal costo, Int32 cveunidad, Decimal precio1, Decimal precio2, Decimal precio3, string foto, string observaciones )
        {
            String Qry =@"INSERT INTO PRODUCTOS(id,clave,descripcion,linea,unidadEntrada,minimo,maximo,moneda,existencias,costo,cveUnidad,precio1,precio2,precio3,foto,observaciones)
            values(@id,@clave,@descripcion,@linea,@unidadentrada,@minimo,@maximo,@moneda,@existencias,@costo,@cveunidad,@precio1,@precio2,@precio3,@foto,@observaciones)";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
		    d.AsignarParametroEntero("@id",id);
		    d.AsignarParametroCadena("@clave",clave);
		    d.AsignarParametroCadena("@descripcion",descripcion);
		    d.AsignarParametroCadena("@linea",linea);
		    d.AsignarParametroCadena("@unidadentrada",unidadentrada);
		    d.AsignarParametroEntero("@minimo",minimo);
		    d.AsignarParametroEntero("@maximo",maximo);
		    d.AsignarParametroCadena("@moneda",moneda);
		    d.AsignarParametroEntero("@existencias",existencias);
		    d.AsignarParametroDecimal("@costo",costo);
		    d.AsignarParametroEntero("@cveunidad",cveunidad);
		    d.AsignarParametroDecimal("@precio1",precio1);
		    d.AsignarParametroDecimal("@precio2",precio2);
		    d.AsignarParametroDecimal("@precio3",precio3);
            d.AsignarParametroCadena("@foto", foto);
            d.AsignarParametroCadena("@observaciones", observaciones);

            d.EjecutarComando();
        }

        public static void actualizarPRODUCTOS(Int32 id, String clave, String descripcion, String linea, String unidadentrada, Int32 minimo, Int32 maximo, String moneda, Int32 existencias, Decimal costo, Int32 cveunidad, Decimal precio1, Decimal precio2, Decimal precio3, string foto, String observaciones)
        {
            String Qry ="UPDATE PRODUCTOS SET clave = @clave, descripcion = @descripcion, linea = @linea, unidadEntrada = @unidadentrada, minimo = @minimo, maximo = @maximo, moneda = @moneda, existencias = @existencias, costo = @costo, cveUnidad = @cveunidad, precio1 = @precio1, precio2 = @precio2, precio3 = @precio3, foto = @foto, observaciones = @observaciones WHERE ID=@id";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
		    d.AsignarParametroEntero("@id",id);
		    d.AsignarParametroCadena("@clave",clave);
		    d.AsignarParametroCadena("@descripcion",descripcion);
		    d.AsignarParametroCadena("@linea",linea);
		    d.AsignarParametroCadena("@unidadentrada",unidadentrada);
		    d.AsignarParametroEntero("@minimo",minimo);
		    d.AsignarParametroEntero("@maximo",maximo);
		    d.AsignarParametroCadena("@moneda",moneda);
		    d.AsignarParametroEntero("@existencias",existencias);
		    d.AsignarParametroDecimal("@costo",costo);
		    d.AsignarParametroEntero("@cveunidad",cveunidad);
		    d.AsignarParametroDecimal("@precio1",precio1);
		    d.AsignarParametroDecimal("@precio2",precio2);
		    d.AsignarParametroDecimal("@precio3",precio3);
            d.AsignarParametroCadena("@foto", foto);
            d.AsignarParametroCadena("@observaciones", observaciones);

            d.EjecutarComando();
        }

        public static void elimiarPRODUCTOS(Int32 id)
        {
            String Qry = @"delete FROM PRODUCTOS where id=@id";
            
            BaseDatos d = new BaseDatos();

            d.Conectar();
            d.CrearComando(Qry); 
            d.AsignarParametroEntero("@id", id);
            d.EjecutarComando();
            d.Desconectar();
        }
        public static List<PRODUCTOS>  seleccionarPRODUCTOS( )
        {
            List<PRODUCTOS> listPRODUCTOS = new List<PRODUCTOS>();
            String Qry = @"SELECT id, clave, descripcion, linea, unidadEntrada, minimo, maximo, moneda, existencias, costo, cveUnidad, precio1, precio2, precio3, foto, observaciones 
                          FROM   PRODUCTOS";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            DbDataReader datosItems = d.EjecutarConsulta();
            while(datosItems.Read())
            {
	            PRODUCTOS objPRODUCTOS = new PRODUCTOS();
	            objPRODUCTOS.id = Convert.ToInt32(datosItems["id"].ToString());
	            objPRODUCTOS.clave = datosItems["clave"].ToString();
	            objPRODUCTOS.descripcion = datosItems["descripcion"].ToString();
	            objPRODUCTOS.linea = datosItems["linea"].ToString();
	            objPRODUCTOS.unidadentrada = datosItems["unidadentrada"].ToString();
	            objPRODUCTOS.minimo = Convert.ToInt32(datosItems["minimo"].ToString());
	            objPRODUCTOS.maximo = Convert.ToInt32(datosItems["maximo"].ToString());
	            objPRODUCTOS.moneda = datosItems["moneda"].ToString();
	            objPRODUCTOS.existencias = Convert.ToInt32(datosItems["existencias"].ToString());
	            objPRODUCTOS.costo = Convert.ToDecimal(datosItems["costo"].ToString());
	            objPRODUCTOS.cveunidad = Convert.ToInt32(datosItems["cveunidad"].ToString());
	            objPRODUCTOS.precio1 = Convert.ToDecimal(datosItems["precio1"].ToString());
	            objPRODUCTOS.precio2 = Convert.ToDecimal(datosItems["precio2"].ToString());
	            objPRODUCTOS.precio3 = Convert.ToDecimal(datosItems["precio3"].ToString());
	            objPRODUCTOS.foto = datosItems["foto"].ToString();
	            objPRODUCTOS.observaciones = datosItems["observaciones"].ToString();
                listPRODUCTOS.Add( objPRODUCTOS);
            }
            datosItems.Close();
            return listPRODUCTOS; 
        }
    }
}