
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------
                            
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using DCE05.Ejemplos.EstrellaUno.AccesoDatos;
namespace Modelo
{
                            
    public class PROVEEDORES
    {
	    Int32	ID_PROVEEDOR;
	    String	NOMBRE;
	    String	DIRECCION;
	    String	TELEFONO;
	    String	CONTACTO;
	    String	EMAIL;
	    String	RFC;

	    public Int32 id_proveedor
	    {
		    get { return this.ID_PROVEEDOR; }
		    set { this.ID_PROVEEDOR = value;}
	    }

	    public String nombre
	    {
		    get { return this.NOMBRE; }
		    set { this.NOMBRE = value;}
	    }

	    public String direccion
	    {
		    get { return this.DIRECCION; }
		    set { this.DIRECCION = value;}
	    }

	    public String telefono
	    {
		    get { return this.TELEFONO; }
		    set { this.TELEFONO = value;}
	    }

	    public String contacto
	    {
		    get { return this.CONTACTO; }
		    set { this.CONTACTO = value;}
	    }

	    public String email
	    {
		    get { return this.EMAIL; }
		    set { this.EMAIL = value;}
	    }

	    public String rfc
	    {
		    get { return this.RFC; }
		    set { this.RFC = value;}
	    }

    }

    public static class metodos_PROVEEDORES
    {

        public void insertarPROVEEDORES(Int32 id_proveedor, String nombre, String direccion, String telefono, String contacto, String email, String rfc)
	        {
	        String Qry =@"INSERT INTO PROVEEDORES(id_proveedor,nombre,direccion,telefono,contacto,email,rfc)
        values(
        @id_proveedor,@nombre,@direccion,@telefono,@contacto,@email,@rfc,)";
	        BaseDatos d = new BaseDatos();
	        d.Conectar();
	        d.CrearComando(Qry);
	        d.AsignarParametroEntero("@id_proveedor",id_proveedor);
	        d.AsignarParametroCadena("@nombre",nombre);
	        d.AsignarParametroCadena("@direccion",direccion);
	        d.AsignarParametroCadena("@telefono",telefono);
	        d.AsignarParametroCadena("@contacto",contacto);
	        d.AsignarParametroCadena("@email",email);
	        d.AsignarParametroCadena("@rfc",rfc);

	        d.EjecutarComando();
        }

        public void actualizarPROVEEDORES(Int32 id_proveedor, String nombre, String direccion, String telefono, String contacto, String email, String rfc)
        {
	        String Qry ="UPDATE PROVEEDORES SET id_proveedor = @id_proveedor, nombre = @nombre, direccion = @direccion, telefono = @telefono, contacto = @contacto, email = @email, rfc = @rfc WHERE ID=@ID";
	        BaseDatos d = new BaseDatos();
	        d.Conectar();
	        d.CrearComando(Qry);
	        d.AsignarParametroEntero("@id_proveedor",id_proveedor);
	        d.AsignarParametroCadena("@nombre",nombre);
	        d.AsignarParametroCadena("@direccion",direccion);
	        d.AsignarParametroCadena("@telefono",telefono);
	        d.AsignarParametroCadena("@contacto",contacto);
	        d.AsignarParametroCadena("@email",email);
	        d.AsignarParametroCadena("@rfc",rfc);

	        d.EjecutarComando();
        }

        public  List<PROVEEDORES>  seleccionarPROVEEDORES(Int32 id_proveedor, String nombre, String direccion, String telefono, String contacto, String email, String rfc)
        {
	        List<PROVEEDORES> listPROVEEDORES = new List<PROVEEDORES>();
	        String Qry =@"SELECT id_proveedor, nombre, direccion, telefono, contacto, email, rfc FROM PROVEEDORES WHERE ID=@ID";
	        BaseDatos d = new BaseDatos();
	        d.Conectar();
	        d.CrearComando(Qry);
	        DbDataReader datosItems = d.EjecutarConsulta();
	        while(datosItems.Read())
	        {
		        PROVEEDORES objPROVEEDORES = new PROVEEDORES();
		        objPROVEEDORES.id_proveedor = Convert.ToInt32(datosItems["id_proveedor"].ToString());
		        objPROVEEDORES.nombre = datosItems["nombre"].ToString();
		        objPROVEEDORES.direccion = datosItems["direccion"].ToString();
		        objPROVEEDORES.telefono = datosItems["telefono"].ToString();
		        objPROVEEDORES.contacto = datosItems["contacto"].ToString();
		        objPROVEEDORES.email = datosItems["email"].ToString();
		        objPROVEEDORES.rfc = datosItems["rfc"].ToString();
		        listPROVEEDORES.Add( objPROVEEDORES);
	        }
	         return listPROVEEDORES; 
        }
    }
}