
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;

namespace Modelo
{
	public class SERIE
	{
		Int32		IDSERIE;
		String		vSERIE;
		String		DESCRIPCION;
		Int32		ULTIMOFILIO;

		public Int32 idserie
		{
			get { return this.IDSERIE; }
			set { this.IDSERIE = value;}
		}

		public String serie
		{
			get { return this.vSERIE; }
			set { this.vSERIE = value;}
		}

		public String descripcion
		{
			get { return this.DESCRIPCION; }
			set { this.DESCRIPCION = value;}
		}

		public Int32 ultimofilio
		{
			get { return this.ULTIMOFILIO; }
			set { this.ULTIMOFILIO = value;}
		}

	}

	public class metodos_SERIE
	{

		public void insertarSERIE(Int32 idserie, String serie, String descripcion, Int32 ultimofilio)
		{
			String Qry =@"INSERT INTO SERIE(idserie,serie,descripcion,ultimoFilio)
values(
@idserie,@serie,@descripcion,@ultimofil )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroEntero("@idserie",idserie);
			d.AsignarParametroCadena("@serie",serie);
			d.AsignarParametroCadena("@descripcion",descripcion);
			d.AsignarParametroEntero("@ultimofilio",ultimofilio);

			d.EjecutarComando();
		}

		public void actualizarFOLIO(Int32 idserie,  Int32 ultimofilio)
		{
			String Qry = "UPDATE serie SET ultimoFolio = ultimoFolio+1 WHERE idserie=@idserie";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
            d.AsignarParametroEntero("@idserie", idserie);
            //d.AsignarParametroEntero("@ultimoFolio", ultimofilio);
			d.EjecutarComando();
		}

        public Int32 seleccionarFOLIO(int id)
        {
            Int32 folio = 0;
            String Qry = @"SELECT ultimoFolio  FROM serie where idserie=@idserie";
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroEntero("@idserie", id);
            DbDataReader datosItems = d.EjecutarConsulta();
            while (datosItems.Read())
            {
                int a = Convert.ToInt32(datosItems["ultimoFolio"].ToString());
                folio = a + 1;
            }
            datosItems.Close();
            d.Desconectar();
            return folio;
        }
        public   List<SERIE>  seleccionarSERIE()
		{
			List<SERIE> listSERIE = new List<SERIE>();
			String Qry =@"SELECT idserie, serie, descripcion, ultimoFolio  FROM serie where status =1";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				SERIE objSERIE = new SERIE();
				objSERIE.idserie = Convert.ToInt32(datosItems["idserie"].ToString());
				objSERIE.serie = datosItems["serie"].ToString();
				objSERIE.descripcion = datosItems["descripcion"].ToString();
				objSERIE.ultimofilio = Convert.ToInt32(datosItems["ultimoFolio"].ToString());
				listSERIE.Add( objSERIE);
			}
            datosItems.Close();
            d.Desconectar();
            return listSERIE; 
		}
	}
}