
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;

namespace Modelo
{
	public class USUARIO
	{
		int		    IDUSUARIO;
		string      vUSUARIO;
		string		CONTRASENA;
		string		ESTATUS;
        string      NIVEL;
		public int idusuario
		{
			get { return this.IDUSUARIO; }
			set { this.IDUSUARIO = value;}
		}

		public string usuario
		{
			get { return this.vUSUARIO; }
			set { this.vUSUARIO = value;}
		}

		public string contrasena
		{
			get { return this.CONTRASENA; }
			set { this.CONTRASENA = value;}
		}

		public string estatus
		{
			get { return this.ESTATUS; }
			set { this.ESTATUS = value;}
		}

        public string nivel
        {
            get { return this.NIVEL; }
            set { this.NIVEL = value; }
        }

    }

	public static  class metodos_USUARIO
	{

		public static void insertarUSUARIO(int idusuario, string usuario, string contrasena, string estatus, string nivel)
		{
			String Qry = @"INSERT INTO usuario(usuario,contrasena,estatus,nivel) values (@usuario,@contrasena,@estatus,@nivel )";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			d.AsignarParametroCadena("@usuario",usuario);
			d.AsignarParametroCadena("@contrasena",contrasena);
			d.AsignarParametroCadena("@estatus",estatus);
            d.AsignarParametroCadena("@nivel", nivel);
            d.EjecutarComando();
            d.Desconectar();

        }

        public static void actualizarUSUARIO(int idusuario, string usuario, string contrasena, string estatus, string nivel)
		{
			String Qry = "UPDATE usuario SET  usuario = @usuario, contrasena = @contrasena, estatus = @estatus, nivel=@nivel WHERE idusuario=@ID";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
            d.AsignarParametroEntero("@ID", idusuario);
            d.AsignarParametroCadena("@usuario", usuario);
            d.AsignarParametroCadena("@contrasena", contrasena);
            d.AsignarParametroCadena("@estatus", estatus);
            d.AsignarParametroCadena("@nivel", nivel);
            d.EjecutarComando();
            d.Desconectar();

        }

        public static USUARIO login(string usuario, string psw)
        {
            USUARIO objUSUARIO=null;
            String Qry = @"SELECT idusuario, usuario, contrasena, estatus, nivel  FROM usuario where usuario=@usuario  and contrasena=@psw";// 
            BaseDatos d = new BaseDatos();
            d.Conectar();
            d.CrearComando(Qry);
            d.AsignarParametroCadena("@usuario", usuario);
            d.AsignarParametroCadena("@psw", psw);
            DbDataReader datosItems = d.EjecutarConsulta();
            while (datosItems.Read())
            {
                objUSUARIO = new USUARIO();
                objUSUARIO.idusuario = Convert.ToInt32(datosItems["idusuario"].ToString());
                objUSUARIO.usuario = datosItems["usuario"].ToString();
                objUSUARIO.contrasena = datosItems["contrasena"].ToString();
                objUSUARIO.estatus = datosItems["estatus"].ToString();
                objUSUARIO.nivel = datosItems["nivel"].ToString();
            }
            datosItems.Close();
            d.Desconectar();

            return objUSUARIO;
        }

        public static List<USUARIO>  seleccionarUSUARIO()
		{
			List<USUARIO> listUSUARIO = new List<USUARIO>();
			String Qry = @"SELECT idusuario, usuario, contrasena, estatus, nivel  FROM usuario";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				USUARIO objUSUARIO = new USUARIO();
				objUSUARIO.idusuario = Convert.ToInt32( datosItems["idusuario"].ToString());
				objUSUARIO.usuario = datosItems["usuario"].ToString();
                objUSUARIO.contrasena = "*****************";//datosItems["contrasena"].ToString();
				objUSUARIO.estatus = datosItems["estatus"].ToString();
                objUSUARIO.nivel = datosItems["nivel"].ToString();
                listUSUARIO.Add( objUSUARIO);
			}
            datosItems.Close();
            d.Desconectar();
            return listUSUARIO; 
		}
	}
}