
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por la herramienta Generador de clases SQL.
//     Versión de runtime:4.0.30319.34209
//
//     Desarrollado por Ismael Almaraz Armeaga
//     ismaelalmaraz@live.com.mx
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using AccesoDatos;

namespace Modelo
{
	public class VERSION
	{
		int		IDVERSION;
		string		NOVERSION;

		public int idversion
		{
			get { return this.IDVERSION; }
			set { this.IDVERSION = value;}
		}

		public string noversion
		{
			get { return this.NOVERSION; }
			set { this.NOVERSION = value;}
		}

	}

	public static class metodos_VERSION
	{
		public static string  seleccionarVERSION()
		{
            String Version = "";
			String Qry = @"SELECT MAX(noversion)  as version  FROM version";
			BaseDatos d = new BaseDatos();
			d.Conectar();
			d.CrearComando(Qry);
			DbDataReader datosItems = d.EjecutarConsulta();
			while(datosItems.Read())
			{
				VERSION objVERSION = new VERSION();
				objVERSION.noversion = datosItems["version"].ToString();
            }
            datosItems.Close();
            d.Desconectar();
            return Version; 
		}
	}
}