//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Modelo.StampSOAP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Application", Namespace="http://facturacion.finkok.com/stamp")]
    public partial class StampSOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback stampOperationCompleted;
        
        private System.Threading.SendOrPostCallback sign_stampOperationCompleted;
        
        private System.Threading.SendOrPostCallback stampedOperationCompleted;
        
        private System.Threading.SendOrPostCallback quick_stampOperationCompleted;
        
        private System.Threading.SendOrPostCallback query_pendingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StampSOAP() {
            this.Url = global::Modelo.Properties.Settings.Default.Modelo_StampSOAP_StampSOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event stampCompletedEventHandler stampCompleted;
        
        /// <remarks/>
        public event sign_stampCompletedEventHandler sign_stampCompleted;
        
        /// <remarks/>
        public event stampedCompletedEventHandler stampedCompleted;
        
        /// <remarks/>
        public event quick_stampCompletedEventHandler quick_stampCompleted;
        
        /// <remarks/>
        public event query_pendingCompletedEventHandler query_pendingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("stamp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("stampResponse", Namespace="http://facturacion.finkok.com/stamp")]
        public stampResponse stamp([System.Xml.Serialization.XmlElementAttribute("stamp", Namespace="http://facturacion.finkok.com/stamp")] stamp stamp1) {
            object[] results = this.Invoke("stamp", new object[] {
                        stamp1});
            return ((stampResponse)(results[0]));
        }
        
        /// <remarks/>
        public void stampAsync(stamp stamp1) {
            this.stampAsync(stamp1, null);
        }
        
        /// <remarks/>
        public void stampAsync(stamp stamp1, object userState) {
            if ((this.stampOperationCompleted == null)) {
                this.stampOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstampOperationCompleted);
            }
            this.InvokeAsync("stamp", new object[] {
                        stamp1}, this.stampOperationCompleted, userState);
        }
        
        private void OnstampOperationCompleted(object arg) {
            if ((this.stampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stampCompleted(this, new stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("sign_stamp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sign_stampResponse", Namespace="http://facturacion.finkok.com/stamp")]
        public sign_stampResponse sign_stamp([System.Xml.Serialization.XmlElementAttribute("sign_stamp", Namespace="http://facturacion.finkok.com/stamp")] sign_stamp sign_stamp1) {
            object[] results = this.Invoke("sign_stamp", new object[] {
                        sign_stamp1});
            return ((sign_stampResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sign_stampAsync(sign_stamp sign_stamp1) {
            this.sign_stampAsync(sign_stamp1, null);
        }
        
        /// <remarks/>
        public void sign_stampAsync(sign_stamp sign_stamp1, object userState) {
            if ((this.sign_stampOperationCompleted == null)) {
                this.sign_stampOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsign_stampOperationCompleted);
            }
            this.InvokeAsync("sign_stamp", new object[] {
                        sign_stamp1}, this.sign_stampOperationCompleted, userState);
        }
        
        private void Onsign_stampOperationCompleted(object arg) {
            if ((this.sign_stampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sign_stampCompleted(this, new sign_stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("stamped", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("stampedResponse", Namespace="http://facturacion.finkok.com/stamp")]
        public stampedResponse stamped([System.Xml.Serialization.XmlElementAttribute("stamped", Namespace="http://facturacion.finkok.com/stamp")] stamped stamped1) {
            object[] results = this.Invoke("stamped", new object[] {
                        stamped1});
            return ((stampedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void stampedAsync(stamped stamped1) {
            this.stampedAsync(stamped1, null);
        }
        
        /// <remarks/>
        public void stampedAsync(stamped stamped1, object userState) {
            if ((this.stampedOperationCompleted == null)) {
                this.stampedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstampedOperationCompleted);
            }
            this.InvokeAsync("stamped", new object[] {
                        stamped1}, this.stampedOperationCompleted, userState);
        }
        
        private void OnstampedOperationCompleted(object arg) {
            if ((this.stampedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stampedCompleted(this, new stampedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("quick_stamp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("quick_stampResponse", Namespace="http://facturacion.finkok.com/stamp")]
        public quick_stampResponse quick_stamp([System.Xml.Serialization.XmlElementAttribute("quick_stamp", Namespace="http://facturacion.finkok.com/stamp")] quick_stamp quick_stamp1) {
            object[] results = this.Invoke("quick_stamp", new object[] {
                        quick_stamp1});
            return ((quick_stampResponse)(results[0]));
        }
        
        /// <remarks/>
        public void quick_stampAsync(quick_stamp quick_stamp1) {
            this.quick_stampAsync(quick_stamp1, null);
        }
        
        /// <remarks/>
        public void quick_stampAsync(quick_stamp quick_stamp1, object userState) {
            if ((this.quick_stampOperationCompleted == null)) {
                this.quick_stampOperationCompleted = new System.Threading.SendOrPostCallback(this.Onquick_stampOperationCompleted);
            }
            this.InvokeAsync("quick_stamp", new object[] {
                        quick_stamp1}, this.quick_stampOperationCompleted, userState);
        }
        
        private void Onquick_stampOperationCompleted(object arg) {
            if ((this.quick_stampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quick_stampCompleted(this, new quick_stampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("query_pending", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("query_pendingResponse", Namespace="http://facturacion.finkok.com/stamp")]
        public query_pendingResponse query_pending([System.Xml.Serialization.XmlElementAttribute("query_pending", Namespace="http://facturacion.finkok.com/stamp")] query_pending query_pending1) {
            object[] results = this.Invoke("query_pending", new object[] {
                        query_pending1});
            return ((query_pendingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void query_pendingAsync(query_pending query_pending1) {
            this.query_pendingAsync(query_pending1, null);
        }
        
        /// <remarks/>
        public void query_pendingAsync(query_pending query_pending1, object userState) {
            if ((this.query_pendingOperationCompleted == null)) {
                this.query_pendingOperationCompleted = new System.Threading.SendOrPostCallback(this.Onquery_pendingOperationCompleted);
            }
            this.InvokeAsync("query_pending", new object[] {
                        query_pending1}, this.query_pendingOperationCompleted, userState);
        }
        
        private void Onquery_pendingOperationCompleted(object arg) {
            if ((this.query_pendingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.query_pendingCompleted(this, new query_pendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamp {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class QueryPendingResult {
        
        private string statusField;
        
        private string xmlField;
        
        private string uuidField;
        
        private string uuid_statusField;
        
        private string next_attemptField;
        
        private string attemptsField;
        
        private string errorField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid_status {
            get {
                return this.uuid_statusField;
            }
            set {
                this.uuid_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string next_attempt {
            get {
                return this.next_attemptField;
            }
            set {
                this.next_attemptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string attempts {
            get {
                return this.attemptsField;
            }
            set {
                this.attemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class query_pendingResponse {
        
        private QueryPendingResult query_pendingResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QueryPendingResult query_pendingResult {
            get {
                return this.query_pendingResultField;
            }
            set {
                this.query_pendingResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class query_pending {
        
        private string usernameField;
        
        private string passwordField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class quick_stampResponse {
        
        private AcuseRecepcionCFDI quick_stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AcuseRecepcionCFDI quick_stampResult {
            get {
                return this.quick_stampResultField;
            }
            set {
                this.quick_stampResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class AcuseRecepcionCFDI {
        
        private string xmlField;
        
        private string uUIDField;
        
        private string faultstringField;
        
        private string fechaField;
        
        private string codEstatusField;
        
        private string faultcodeField;
        
        private string satSealField;
        
        private Incidencia[] incidenciasField;
        
        private string noCertificadoSATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SatSeal {
            get {
                return this.satSealField;
            }
            set {
                this.satSealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Incidencia[] Incidencias {
            get {
                return this.incidenciasField;
            }
            set {
                this.incidenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NoCertificadoSAT {
            get {
                return this.noCertificadoSATField;
            }
            set {
                this.noCertificadoSATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="apps.services.soap.core.views")]
    public partial class Incidencia {
        
        private string idIncidenciaField;
        
        private string rfcEmisorField;
        
        private string uuidField;
        
        private string codigoErrorField;
        
        private string workProcessIdField;
        
        private string mensajeIncidenciaField;
        
        private string extraInfoField;
        
        private string noCertificadoPacField;
        
        private string fechaRegistroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdIncidencia {
            get {
                return this.idIncidenciaField;
            }
            set {
                this.idIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WorkProcessId {
            get {
                return this.workProcessIdField;
            }
            set {
                this.workProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MensajeIncidencia {
            get {
                return this.mensajeIncidenciaField;
            }
            set {
                this.mensajeIncidenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExtraInfo {
            get {
                return this.extraInfoField;
            }
            set {
                this.extraInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NoCertificadoPac {
            get {
                return this.noCertificadoPacField;
            }
            set {
                this.noCertificadoPacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class quick_stamp {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stampedResponse {
        
        private AcuseRecepcionCFDI stampedResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AcuseRecepcionCFDI stampedResult {
            get {
                return this.stampedResultField;
            }
            set {
                this.stampedResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stamped {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class sign_stampResponse {
        
        private AcuseRecepcionCFDI sign_stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AcuseRecepcionCFDI sign_stampResult {
            get {
                return this.sign_stampResultField;
            }
            set {
                this.sign_stampResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class sign_stamp {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://facturacion.finkok.com/stamp")]
    public partial class stampResponse {
        
        private AcuseRecepcionCFDI stampResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AcuseRecepcionCFDI stampResult {
            get {
                return this.stampResultField;
            }
            set {
                this.stampResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void stampCompletedEventHandler(object sender, stampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stampResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stampResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void sign_stampCompletedEventHandler(object sender, sign_stampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sign_stampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sign_stampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sign_stampResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sign_stampResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void stampedCompletedEventHandler(object sender, stampedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stampedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stampedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stampedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stampedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void quick_stampCompletedEventHandler(object sender, quick_stampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quick_stampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quick_stampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public quick_stampResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((quick_stampResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void query_pendingCompletedEventHandler(object sender, query_pendingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class query_pendingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal query_pendingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public query_pendingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((query_pendingResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591